### ISSUE TITLE
Django Buddy

### ISSUE THREAD

**Issue by kori73** [gjergjk71/django-messages#2]
Hello, I would like to join as a Django buddy. I have completed two beginner projects on Django.
- Blog (of course)
- Notes 

Working on these projects I have learnt about the basics of the Django, authentication, creating forms, sign-up/login/logout features, Django messages.

My goals are as follows.
- Having a fundamental understanding of Django
- Creating web scraping applications
- Creating data analysis and machine learning applications (computer vision and natural language processing would be great)
- Web automation with Django

I think it would be great to learn Django and the amazing libraries of Python together.
Let me know what you think.

**Comment by gjergjk71** [comment]
Do you use discord? gjergjk71#6198
